### ISSUE TITLE
The experiment on rag_truth dataset is not valid.

### ISSUE THREAD

**Issue by PolyU-ShuhaoLi** [GaurangSriramanan/LLM_Check_Hallucination_Detection#2]
Hi, thanks for your repository.
But I think the file "rag_truth/dataset/response_summary.jsonl" is not upload. This file is used at the line 15, utils_ragtruth.py.
Could you please upload the file? Then I can do my new work based on your code and paper.
Thanks a lot :)

**Comment by GaurangSriramanan** [comment]
Hi, thanks so much for your interest in our work! 

In this paper, we use datasets that were released by other authors on previous publications under their own licensing terms, and thus we do not include those exact dataset files in our repo. We thus kindly request you to download them from their original sources as we explain in the "Code Setup and Organization" section of our ReadMe. 

For the RagTruth dataset, please find the dataset files here: https://github.com/ParticleMedia/RAGTruth/tree/main/dataset

In the earlier version of the RagTruth dataset, both the source_info and the responses were combined into a single file called "rag_truth/dataset/response_summary.jsonl", which is what we used during our experiments. 
But for some reason this has been changed in the latest version of the RagTruth repo, and the data is presented in two separate files called "[response.jsonl](https://github.com/ParticleMedia/RAGTruth/blob/main/dataset/response.jsonl)" and "[source_info.jsonl](https://github.com/ParticleMedia/RAGTruth/blob/main/dataset/source_info.jsonl)". 
The "source_id" can be matched between the two files to find the respective source-response pairs and their corresponding annotations. In this set of files, different task_types have been combined as well, so please utilize the subset of data with "task_type": "Summary" and "split": "train", since we used that for our experiments. Thus, we effectively use the samples with "source_id" starting from "15592" and ending with "13598".

**Comment by PolyU-ShuhaoLi** [comment]
Thank you for your explaination. It helps me a lot :)
